server.port=${PORT:8081}

camunda.client.mode=${CAMUNDA_MODE:self-managed}

camunda.client.grpc-address=${CAMUNDA_GRPC_ADDRESS:http://localhost:26500}

camunda.client.rest-address=${CAMUNDA_REST_ADDRESS:http://localhost:8080}

camunda.client.auth.method=${CAMUNDA_AUTH_METHOD:none}