server.port=${PORT:8081}

camunda.client.mode=saas

camunda.client.auth.client-id=${CAMUNDA_CLIENT_ID}

camunda.client.auth.client-secret=${CAMUNDA_CLIENT_SECRET}

camunda.client.cloud.cluster-id=${CAMUNDA_CLUSTER_ID}

camunda.client.cloud.region=${CAMUNDA_CLUSTER_REGION}